<a href="https://colab.research.google.com/github/Tarnished2/DataScientist/blob/main/Exercise_2_Muklis_Pramaditya%20Ardian%20Saputra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h4>Lakukan latihan berikut<h4>

Import dataset iris yang disediakan oleh package sklearn, beri nama df. Kemudian lakukan: (maks skor 15)
- Tampilkan 5 dataset teratas dan 5 terbawah
-	Lakukan filter untuk mendapatkan Sepal.Length antara 4-5 dan Sepal.Width antara 2-3
-	Hitung jumlah species permasing-masing kelasnya (gunakan cara count dan groupby)
-	Filter berdasarkan setosa, simpan dalam df_setosa


In [ ]:
import pandas as pd
df = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

- menampilkan 5 data teratas

In [ ]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

- menampilkan 5 data terbawah

In [ ]:
df.tail()

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

- filter untuk mendapatkan Sepal.Length antara 4-5

In [ ]:
df_filtered1 = df[(df['sepal.length'] >= 4) & (df['sepal.length'] <= 5)]
print(df_filtered1)

     sepal.length  sepal.width  petal.length  petal.width     variety
1             4.9          3.0           1.4          0.2      Setosa
2             4.7          3.2           1.3          0.2      Setosa
3             4.6          3.1           1.5          0.2      Setosa
4             5.0          3.6           1.4          0.2      Setosa
6             4.6          3.4           1.4          0.3      Setosa
7             5.0          3.4           1.5          0.2      Setosa
8             4.4          2.9           1.4          0.2      Setosa
9             4.9          3.1           1.5          0.1      Setosa
11            4.8          3.4           1.6          0.2      Setosa
12            4.8          3.0           1.4          0.1      Setosa
13            4.3          3.0           1.1          0.1      Setosa
22            4.6          3.6           1.0          0.2      Setosa
24            4.8          3.4           1.9          0.2      Setosa
25            5.0   

- filter untuk mendapatkan Sepal.Width antara 2-3

In [ ]:
df_filtered2 = df[(df['sepal.width'] >= 2) & (df['sepal.width'] <= 3)]
print(df_filtered2)

     sepal.length  sepal.width  petal.length  petal.width    variety
1             4.9          3.0           1.4          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
12            4.8          3.0           1.4          0.1     Setosa
13            4.3          3.0           1.1          0.1     Setosa
25            5.0          3.0           1.6          0.2     Setosa
..            ...          ...           ...          ...        ...
142           5.8          2.7           5.1          1.9  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[83 rows x 5 columns]


- hitung jumlah species per masing2 kelas

sepal.length

In [ ]:
count_species = df.groupby('sepal.length').size()
print(count_species)

petal.length
1.0     1
1.1     1
1.2     2
1.3     7
1.4    13
1.5    13
1.6     7
1.7     4
1.9     2
3.0     1
3.3     2
3.5     2
3.6     1
3.7     1
3.8     1
3.9     3
4.0     5
4.1     3
4.2     4
4.3     2
4.4     4
4.5     8
4.6     3
4.7     5
4.8     4
4.9     5
5.0     4
5.1     8
5.2     2
5.3     2
5.4     2
5.5     3
5.6     6
5.7     3
5.8     3
5.9     2
6.0     2
6.1     3
6.3     1
6.4     1
6.6     1
6.7     2
6.9     1
dtype: int64


sepal.width

In [ ]:
count_species = df.groupby('sepal.width').size()
print(count_species)

sepal.width
2.0     1
2.2     3
2.3     4
2.4     3
2.5     8
2.6     5
2.7     9
2.8    14
2.9    10
3.0    26
3.1    11
3.2    13
3.3     6
3.4    12
3.5     6
3.6     4
3.7     3
3.8     6
3.9     2
4.0     1
4.1     1
4.2     1
4.4     1
dtype: int64


petal.length

In [ ]:
count_species = df.groupby('petal.length').size()
print(count_species)

petal.length
1.0     1
1.1     1
1.2     2
1.3     7
1.4    13
1.5    13
1.6     7
1.7     4
1.9     2
3.0     1
3.3     2
3.5     2
3.6     1
3.7     1
3.8     1
3.9     3
4.0     5
4.1     3
4.2     4
4.3     2
4.4     4
4.5     8
4.6     3
4.7     5
4.8     4
4.9     5
5.0     4
5.1     8
5.2     2
5.3     2
5.4     2
5.5     3
5.6     6
5.7     3
5.8     3
5.9     2
6.0     2
6.1     3
6.3     1
6.4     1
6.6     1
6.7     2
6.9     1
dtype: int64


petal.width

In [ ]:
count_species = df.groupby('petal.width').size()
print(count_species)

petal.width
0.1     5
0.2    29
0.3     7
0.4     7
0.5     1
0.6     1
1.0     7
1.1     3
1.2     5
1.3    13
1.4     8
1.5    12
1.6     4
1.7     2
1.8    12
1.9     5
2.0     6
2.1     6
2.2     3
2.3     8
2.4     3
2.5     3
dtype: int64


variety

In [ ]:
count_species = df.groupby('variety').size()
print(count_species)

variety
Setosa        50
Versicolor    50
Virginica     50
dtype: int64


- Filter berdasarkan setosa, simpan dalam df_setosa

In [ ]:
df_setosa = df[(df['sepal.width'] == 0) & (df['sepal.length'] == 0) & (df['petal.width'] == 0) & (df['petal.length'] == 0) & (df['variety'] == 0)]
print(df_setosa)

Empty DataFrame
Columns: [sepal.length, sepal.width, petal.length, petal.width, variety]
Index: []


<h4> Lakukan Latihan Berikut </h4>




1. Bacalah dataset 'retail_raw_test.csv' dan tampilkan 10 elemen pertama dataset tersebut dengan index columnnya yaitu order_date.

2. Hapuslah kolom order_id dan product_id dan tampilkan data retail pada kota Jakarta Pusat atau Yogyakarta

3. Buatlah kolom "total_price" sebagai hasil perkalian quantity dengan item_price dan "city/province" dari gabungan city & province. kemudian hapus kolom city dan province.

4. Tampilkan retail yang terjadi mulai tanggal 1 Agustus 2019 sampai 30 Agustus 2019

5. Tampilkan banyakanya tiap brand dengan mengelompokan data berdasarkan kolom brand 


1. baca datasheet

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/SIB/1. Basic Python Programming/retail_raw_test.csv', index_col='order_date')
print(df)

            order_id  customer_id           city     province    brand  \
order_date                                                               
2019-12-11   1730350        13447      Surakarta  Jawa Tengah  BRAND_F   
2019-10-18   1704211        16128  Jakarta Pusat  DKI Jakarta  BRAND_H   
2019-08-07   1679695        16225     Yogyakarta   Yogyakarta  BRAND_H   
2019-04-18   1642990        16022  Jakarta Pusat  DKI Jakarta  BRAND_M   
2019-04-16   1642138        12720       Denpasar         Bali  BRAND_P   
...              ...          ...            ...          ...      ...   
2019-10-17   1703389        16395       Semarang  Jawa Tengah  BRAND_R   
2019-01-08   1616509        12748  Jakarta Utara  DKI Jakarta  BRAND_B   
2019-11-13   1715698        16885         Bekasi   Jawa Barat  BRAND_S   
2019-07-03   1668061        13571  Jakarta Utara  DKI Jakarta  BRAND_W   
2019-11-26   1721713        14505  Jakarta Timur  DKI Jakarta  BRAND_J   

            quantity  item_price prod

menampilkan 10 elemen pertama

In [ ]:
df.head(10)

order_id  customer_id             city     province    brand  \
order_date                                                                 
2019-12-11   1730350        13447        Surakarta  Jawa Tengah  BRAND_F   
2019-10-18   1704211        16128    Jakarta Pusat  DKI Jakarta  BRAND_H   
2019-08-07   1679695        16225       Yogyakarta   Yogyakarta  BRAND_H   
2019-04-18   1642990        16022    Jakarta Pusat  DKI Jakarta  BRAND_M   
2019-04-16   1642138        12720         Denpasar         Bali  BRAND_P   
2019-12-08   1728226        15861        Tangerang       Banten  BRAND_L   
2019-04-21   1643581        17625          Bandung   Jawa Barat  BRAND_H   
2019-08-23   1685443        14854  Jakarta Selatan  DKI Jakarta  BRAND_S   
2019-10-20   1704610        13435            Depok   Jawa Barat  BRAND_R   
2019-03-04   1630102        18225        Surakarta  Jawa Tengah  BRAND_P   

            quantity  item_price product_id  
order_date                                   
2019-12-11        24      113000      P1374  
2019-10-18        12      747000      P1679  
2019-08-07         6      590000      P1708  
2019-04-18         4     2445000      P2279  
2019-04-16         6     6312000      P2803  
2019-12-08         2      590000      P2102  
2019-04-21         2      240000      P1768  
2019-08-23         1    13995000      P3390  
2019-10-20        10      590000      P3022  
2019-03-04        24      205000      P2443

2. hapuslah kolom order_id dan product_id dan tampilkan data retail pada kota Jakarta Pusat atau Yogyakarta

In [ ]:
df = df.drop(['order_id','product_id'], axis=1)
df = df[(df['city'] == 'Jakarta Pusat') | (df['city'] == 'Yogyakarta')]
print(df)

            customer_id           city     province    brand  quantity  \
order_date                                                               
2019-10-18        16128  Jakarta Pusat  DKI Jakarta  BRAND_H        12   
2019-08-07        16225     Yogyakarta   Yogyakarta  BRAND_H         6   
2019-04-18        16022  Jakarta Pusat  DKI Jakarta  BRAND_M         4   
2019-01-13        17913  Jakarta Pusat  DKI Jakarta  BRAND_R         1   
2019-07-23        12747  Jakarta Pusat  DKI Jakarta  BRAND_W        24   
...                 ...            ...          ...      ...       ...   
2019-12-05        13319     Yogyakarta   Yogyakarta  BRAND_C        12   
2019-11-04        16133  Jakarta Pusat  DKI Jakarta  BRAND_R         2   
2019-10-22        13644     Yogyakarta   Yogyakarta  BRAND_P        12   
2019-09-24        17675  Jakarta Pusat  DKI Jakarta  BRAND_S         4   
2019-10-08        16279  Jakarta Pusat  DKI Jakarta  BRAND_J         4   

            item_price  
order_date  

3. Buatlah kolom "total_price" sebagai hasil perkalian quantity dengan item_price dan "city/province" dari gabungan city & province.

In [ ]:
df['total_price'] = df['quantity']*df['item_price']
df['city/province'] = df['city'] + '/' + df['province']
print(df)

            customer_id           city     province    brand  quantity  \
order_date                                                               
2019-10-18        16128  Jakarta Pusat  DKI Jakarta  BRAND_H        12   
2019-08-07        16225     Yogyakarta   Yogyakarta  BRAND_H         6   
2019-04-18        16022  Jakarta Pusat  DKI Jakarta  BRAND_M         4   
2019-01-13        17913  Jakarta Pusat  DKI Jakarta  BRAND_R         1   
2019-07-23        12747  Jakarta Pusat  DKI Jakarta  BRAND_W        24   
...                 ...            ...          ...      ...       ...   
2019-12-05        13319     Yogyakarta   Yogyakarta  BRAND_C        12   
2019-11-04        16133  Jakarta Pusat  DKI Jakarta  BRAND_R         2   
2019-10-22        13644     Yogyakarta   Yogyakarta  BRAND_P        12   
2019-09-24        17675  Jakarta Pusat  DKI Jakarta  BRAND_S         4   
2019-10-08        16279  Jakarta Pusat  DKI Jakarta  BRAND_J         4   

            item_price  total_price  

hapus kolom city dan province

In [ ]:
df = df.drop(['city', 'province'], axis=1)
print(df)

            customer_id    brand  quantity  item_price  total_price  \
order_date                                                            
2019-10-18        16128  BRAND_H        12      747000      8964000   
2019-08-07        16225  BRAND_H         6      590000      3540000   
2019-04-18        16022  BRAND_M         4     2445000      9780000   
2019-01-13        17913  BRAND_R         1     1045000      1045000   
2019-07-23        12747  BRAND_W        24     2375000     57000000   
...                 ...      ...       ...         ...          ...   
2019-12-05        13319  BRAND_C        12     1745000     20940000   
2019-11-04        16133  BRAND_R         2     2987000      5974000   
2019-10-22        13644  BRAND_P        12      740000      8880000   
2019-09-24        17675  BRAND_S         4     1745000      6980000   
2019-10-08        16279  BRAND_J         4      740000      2960000   

                        city/province  
order_date                          

4. Tampilkan retail yang terjadi mulai tanggal 1 Agustus 2019 sampai 30 Agustus 2019

In [ ]:
start_date = '2019-08-01'
end_date = '2019-08-30'
df = df.sort_index()
df.loc[start_date : end_date]

customer_id    brand  quantity  item_price  total_price  \
order_date                                                            
2019-08-01        15150  BRAND_W        25      159000      3975000   
2019-08-01        17611  BRAND_S         2     1745000      3490000   
2019-08-01        17069  BRAND_A        12      450000      5400000   
2019-08-02        14918  BRAND_S        24      240000      5760000   
2019-08-02        14918  BRAND_W        12     1045000     12540000   
2019-08-04        13230  BRAND_E         2      450000       900000   
2019-08-04        17126  BRAND_C        10      159000      1590000   
2019-08-04        17126  BRAND_F         3      303000       909000   
2019-08-05        14796  BRAND_A         2      747000      1494000   
2019-08-05        15577  BRAND_L         3      590000      1770000   
2019-08-05        13098  BRAND_B        25      159000      3975000   
2019-08-05        15265  BRAND_Z        16      450000      7200000   
2019-08-05        13394  BRAND_A        24      205000      4920000   
2019-08-07        16225  BRAND_H         6      590000      3540000   
2019-08-07        13263  BRAND_L         2      590000      1180000   
2019-08-07        14498  BRAND_P         4      520000      2080000   
2019-08-07        16843  BRAND_D        18      289000      5202000   
2019-08-07        15752  BRAND_L         5      590000      2950000   
2019-08-07        16843  BRAND_L        10      590000      5900000   
2019-08-08        14562  BRAND_F         6      590000      3540000   
2019-08-08        14562  BRAND_H        12      240000      2880000   
2019-08-08        14716  BRAND_J         3      740000      2220000   
2019-08-08        17738  BRAND_R        12      590000      7080000   
2019-08-11        17774  BRAND_P         2     1745000      3490000   
2019-08-11        16180  BRAND_R         6     1150000      6900000   
2019-08-11        16931  BRAND_L         3      590000      1770000   
2019-08-11        16931  BRAND_M         3      303000       909000   
2019-08-13        16128  BRAND_S         8      303000      2424000   
2019-08-14        17229  BRAND_S         2      205000       410000   
2019-08-14        15039  BRAND_E         4     4475000     17900000   
2019-08-15        14298  BRAND_A        12      904000     10848000   
2019-08-15        14298  BRAND_M        24      149000      3576000   
2019-08-15        15370  BRAND_P         6      747000      4482000   
2019-08-18        15708  BRAND_C         2     1465000      2930000   
2019-08-18        13230  BRAND_P        10      310000      3100000   
2019-08-18        14019  BRAND_T         6      695000      4170000   
2019-08-19        15218  BRAND_J        30      740000     22200000   
2019-08-19        14796  BRAND_S         2      310000       620000   
2019-08-20        15159  BRAND_L        12      590000      7080000   
2019-08-20        16951  BRAND_P         6     1045000      6270000   
2019-08-22        14973  BRAND_S         4     2795000     11180000   
2019-08-22        16843  BRAND_L        20      590000     11800000   
2019-08-22        16843  BRAND_D        12      450000      5400000   
2019-08-26        16984  BRAND_L         1      904000       904000   
2019-08-26        16984  BRAND_U         6      450000      2700000   
2019-08-27        14076  BRAND_S         2      303000       606000   
2019-08-27        14076  BRAND_R         3      310000       930000   
2019-08-27        14076  BRAND_A         1      310000       310000   
2019-08-28        13486  BRAND_P        10      590000      5900000   
2019-08-28        17514  BRAND_D        10       79000       790000   
2019-08-29        16180  BRAND_G         6     1045000      6270000   
2019-08-29        14535  BRAND_W        12     1045000     12540000   
2019-08-29        14535  BRAND_I         1     2987000      2987000   
2019-08-29        14562  BRAND_C         1     4475000      4475000   
2019-08-30        17377  BRAND_R    

5. Tampilkan banyakanya tiap brand dengan mengelompokan data berdasarkan kolom brand

In [ ]:
df.groupby('brand').size().reset_index(name='counts')

brand  counts
0   BRAND_A      43
1   BRAND_B      41
2   BRAND_C      57
3   BRAND_D      25
4   BRAND_E      14
5   BRAND_F      35
6   BRAND_G      40
7   BRAND_H      42
8   BRAND_I      11
9   BRAND_J      34
10  BRAND_K       6
11  BRAND_L      37
12  BRAND_M      26
13  BRAND_N       3
14  BRAND_O       8
15  BRAND_P      92
16  BRAND_Q       1
17  BRAND_R      45
18  BRAND_S      91
19  BRAND_T      26
20  BRAND_U       1
21  BRAND_V      13
22  BRAND_W      40
23  BRAND_Y       1
24  BRAND_Z       4

<h4>Lakukan latihan berikut<h4>
Diberikan angka random sebagai berikut (0.26, 0.96, 0.63, 0.5 , 0.31, 0.94, 0.71, 0.81, 0.11). Simpanlah kedalam array1 yang merupakan numpy array berdimensi 3x3 dengan menggunakan nested loop for dan while (sehingga ada 2 jawaban) ! Urutan angka bebas

- For loop

In [ ]:
import numpy as np

random_nums = [0.26, 0.96, 0.63, 0.5, 0.31, 0.94, 0.71, 0.81, 0.11]
array1 = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        array1[i][j] = random_nums[i*3+j]
        
print(array1)

[[0.26 0.96 0.63]
 [0.5  0.31 0.94]
 [0.71 0.81 0.11]]


- While loop

In [ ]:
import numpy as np

random_nums = [0.26, 0.96, 0.63, 0.5, 0.31, 0.94, 0.71, 0.81, 0.11]
array1 = np.zeros((3, 3))

i, j = 0, 0
while i < 3:
    while j < 3:
        array1[i][j] = random_nums[i*3+j]
        j += 1
    i += 1
    j = 0

print(array1)

[[0.26 0.96 0.63]
 [0.5  0.31 0.94]
 [0.71 0.81 0.11]]
